info:
  contact: {}
paths:
  /auth/login:
    get:
      consumes:
      - application/json
      description: login
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: login get auth code
      tags:
      - example
swagger: "2.0"
